# Generated by Django 3.1.1 on 2020-09-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['name']},
        ),
    ]
