# Generated by Django 3.1.1 on 2020-09-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_objective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='text',
            new_name='comment',
        ),
    ]
