# Generated by Django 3.1.1 on 2020-09-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0005_auto_20200905_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='goal.goal'),
        ),
    ]
