# Generated by Django 3.1.1 on 2020-09-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_auto_20200905_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['comment']},
        ),
    ]
