# Generated by Django 3.1.1 on 2020-09-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0007_auto_20200908_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
