# Generated by Django 3.1.1 on 2020-09-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_auto_20200908_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
